### ISSUE TITLE
Incorrect detection of compiler during Autotools build

### ISSUE THREAD

**Issue by Vort** [Qucs/qucs#1001]
In configure.ac file test, which selects if Clang or GCC is used, exists.
But it is wrong: regardless of used compiler, script acts as if Clang is used.
https://github.com/Qucs/qucs/blob/13de648ebbfe7dfbd964f1dd7e7524e365ca0079/qucs/configure.ac#L220

Discussion in PR #999 contains propositions on how to fix this problem.

**Comment by felix-salfelder** [comment]
#999 has been merged.
