### ISSUE TITLE
Can't run simulation

### ISSUE THREAD

**Issue by derei** [Qucs/qucs#1003]
I tried following some tutorials on YouTube (unfortunately, all of them use outdated qucs versions), but for some reasons, I can't get the same results, my simulation won't result in any meaningful values in the table. 

I'd appreciate any help right now (if you know about some tutorial using a newer version of qucs).

**Comment by oxmon-2500** [comment]
Pls attach the schematic file (name.sch) of your try

**Comment by derei** [comment]
![qucs](https://user-images.githubusercontent.com/34483372/80005988-3409d880-84bc-11ea-869a-07af0645be2c.png)
the initial value of the power supply and the resistor had been changed, but I couldn't do anything to get updated values in the table (even redoing the table won't update).

I had another simulation earlier, which was even worse, but I deleted out of anger.

sch file attached here:
[test.zip](https://github.com/Qucs/qucs/files/4517406/test.zip)

**Comment by oxmon-2500** [comment]
After every change the values, simulate button must be pressed again,  dpl window closed. Simulation do not start automatically.

**Comment by derei** [comment]
Thanks, anyway it looks like dpl tab doesn't have to be manually closed. Pressing Simulation would update the values.

I've got this warning: WARNING: DC1: inserted virtual resistance at node `_net1' connected to [R1,Voltage,V1]

Not sure what it means

**Comment by oxmon-2500** [comment]
The circuit must be connected to ground
![qucs_test_1004_gnd](https://user-images.githubusercontent.com/14089554/80020664-b1901180-84d9-11ea-80a5-82dcc6910a25.png)

**Comment by derei** [comment]
Any proper documentation available to explain this software? Help seems basic.
For example, what is the purpose for the dpl tab that gets created with the simulation? the whole window looks empty, nothing to show...yet every time when simulation button gets pressed, the software switches to it

**Comment by miguel9554** [comment]
@derei, I'm new to Qucs as well as you. I found the [official documentation](http://qucs.sourceforge.net/docs.html) to have useful resources. The [Getting Started](http://qucs.sourceforge.net/docs/tutorial/getstarted.pdf) tutorial offers a nice introduction to the sotware and how to use it. You alse have specific tutorials for each topic.
