### ISSUE TITLE
Version String Missing in .dat Files in Qucs Version 0.0.22

### ISSUE THREAD

**Issue by cweickhmann** [Qucs/qucs#1012]
I observed that in Qucs 0.0.22, the `<Qucs Dataset >` tag is not complete. In particular, it is missing the version string (in this case 0.0.22) which makes e.g. `qucsconv` refuse working.

**MWE**
* Create file (here `single_coil.sch`)
* Place any simple setup in there (in my case: DC source, resistor, GND, connect them, add a DC Simulation)
* Check the `single_coil.dat` file.

In 0.0.19, the first line reads
```
<Qucs Dataset 0.0.19>
```

In 0.0.22, the first line reads
```
<Qucs Dataset >
```

This makes qucsconv hickup and refuse to work in a on first sight rather cryptic error message (`line 1: syntax error, unexpected '<', expecting Version`).

**Comment by Rmano** [comment]
Hmmm... QUCS is at 0.0.20. Are you mixing this project with https://github.com/ra3xdh/qucs_s/tree/0.0.22 ?

**Comment by cweickhmann** [comment]
Yup. You're right.
