### ISSUE TITLE
How can I compile QUCS using Qt5?

### ISSUE THREAD

**Issue by AlmuHS** [Qucs/qucs#1057]
I'm trying to compile QUCS in Debian, using Qt5, following the instruction of the docs. 
But, when I execute configure script, it ask me to using Qt4.

How can I compile QUCS with Qt5?

**Comment by felix-salfelder** [comment]
> How can I compile QUCS with Qt5?

Short answer: You can't, it's not implemented. See #1006 and the like for longer answers.

closing (duplicate)
