### ISSUE TITLE
QUCS-Modular - compilation with cmake has problem with "no such file"

### ISSUE THREAD

**Issue by Circa-Tree** [Qucs/qucs#1060]
The README.md has instructions for using cmake as an option to compile QUCS-Modular.

1) Using CMake QT Gui to compile QUCS-Modular, there is an error reported ;

/cmake.stale/legacy/action/../../../legacy/action/MakeList
CMake Error at readMakeList.txt:20 (file):
  file failed to open for reading (No such file or directory):

The only file at that location is "CMakeLists.txt".

Q1) Is the wrong file being called, or is it incorrectly named, or what else might be going wrong?

2) The "CMakeLists.txt" file has a couple of lines with questionmarks, such as ;

"19 # TODO: define once?"
"25 # really?"
as well as 
"35 # TODO figure out way to copy plugin into expected QUCS_PLUGPATH"

Q2) Is this file sufficient for successful compilation, or is there a bit more work required to complete it?

**Comment by felix-salfelder** [comment]
On Sun, Oct 31, 2021 at 04:28:36AM -0700, Circa-Tree wrote:
> The README.md has instructions for using cmake as an option to compile QUCS-Modular.

These instructions are wishful thinking. Perhaps an update is needed.
The cmake files should be in a separate place, and the README file
should/could reference them.

> Q2) Is this file sufficient for successful compilation, or is there a
> bit more work required to complete it?

It never really worked, and some parts might be out of date. See
cmake.stale/README for a tentative, possibly incomplete TODO list.

I don't really care, which build system you prefer. I can't maintain
more than one. At the moment, when in doubt, build with autotools.

This situation won't change until there is a working alternative...
