### ISSUE TITLE
Refactor worklist

### ISSUE THREAD

**Issue by yodalee** [Qucs/qucs#125]
Recently I tried to do some work on QGraphicsView, I found it extremely difficult. The reason is that qucsapp, schematic, textdoc, and some dialog is linked to each other closely. Move Q3scrollview to QGraphicsView will cause many hard, inefficient work. 
My suggestion is that: we first concentrate on some small part refactor, gradually split everything apart. We can create a new branch to do this and merge them into master periodically. Or just keep the master branch, and merge refactor every PR into master.
******
I will keep this issue to record the refactor works can be done, so anyone wanna help can leave what you are doing now in order to prevent duplicated work with other. Also, any proposal of refactor can be post below, I will add them into the checklist. Also, work already being merged will be removed.
<b>Many work to do, any help is welcome. <i>Instance dungeon need more player</i></b>
******
The old issue about Qt3 remove #101 is closed. Merged with this issues:
******

## Refactor Work

- [x] Refactor SearchDialog: Removing access to QucsApp in searchdialog. Replace by emit signal and connect to TextDoc slot. See PR #124 
- [x] <b>I'm currently doing this</b> Refactor qucsApp printer.
Printer function is now implemented in qucs.cpp (and main.cpp, which is I did (._.) ) Move it to a independent class printer. There should be two derived printer, one implement print to document, and another print to svg. After refactor, the `QucsApp::printCurrentDocument` and `slotSaveSchematicToGraphicsFile` should only do 1: create Printer, 2: put file into printer, 3: done. So does main.cpp
- [ ] Move updatePortNumber into schematic. It seems this function is strongly related to schematic file (model). Try to make it a function in schematic.cpp. Remember that QucsApp shouldn't know how Schematic is implemented.
- [ ] Split `project manager` and QucsApp. Currently QucsApp handle every function about project. Again not a good design. We need a `project manager` class and QucsApp only hold a pointer to these object. The class should have slot to create/open/delete project, also managing files in the project. Function like `QucsApp::readProjectFiles` should just a function call to `project manager`
- [ ] Element interface need refactor, search `info` in qucs.cpp, you can find that is a function pointer call to get the component name and component bitmap. I think this kind implementation is not necessary, the name and bitmap can just be a property of the component class, and call a getter to get the name.

## Large Goal
This is some large goal which cannot be done in one PR, just list here so everyone know what we are doing:
* Split Schematic with Schematic file.
* Split Textdoc with Textdoc file.
Now these two derive from a view class and QucsDoc (schematic/Q3ScrollView, TextDoc/QPlainTextEdit), we need to separate them into view and QucsDoc. I think it will become a view class hold a pointer to a QucsDoc. View class care nothing about file. It just print out something on the screen.
* schematic submission: dialog/settingdialog
* textdoc submission: dialog/vasettingdialog
* textdoc submission: dialog/digisettingidialog
These three submissions is that, these three dialog set data in QucsDoc, which related to Schematic and TextDoc. In the end they should simply care about schematic_file and textdoc_file.

## Remove Q3ptrlist
Not conflict with refactor work "theoretically". Usually very hard work in "reality"
- [ ] Move `Q3PtrList<Painting> SymbolPaints` in Schematic 
- [ ] Schematic `Q3PtrList<Wire>`
- [ ] Schematic `Q3PtrList<Node>`
- [ ] Schematic `Q3PtrList<Diagram>`
- [ ] Move `Q3PtrList<DataX>` `Q3PtrList<Graph>` Diagrams/graph and Diagrams/diagramdialog:
- [ ] Schematic `Q3PtrList<Component>`
- [ ] Move `Q3PtrList<Property>` in components/component.h
- [x] Schematic `Q3PtrList ElementCache`, #145 
- [ ] qucs_action `Q3PtrList<Component>`
- [ ] mouseaction Some function about move elements.

**Comment by yodalee** [comment]
I think I will close this, and split mission into separate issues.
Allow new coming easy to find what needs to do.

**Comment by guitorri** [comment]
@yodalee rebased again in https://github.com/guitorri/qucs/tree/QGraphicView-port-exploration
