### ISSUE TITLE
OpAmp from the Ideal library generate netlist with syntax error

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#140]
There is a bug on the OpAmp from the Ideal library. See https://sourceforge.net/p/qucs/discussion/311050/thread/cccc70a5/

In the netlist line 5 it complains about the following:
```
R:R1 _net1 _net3 R="1E3/sqrt(2*pi*fg)" Temp="26.85" Tc1="0.0" Tc2="0.0" Tnom="26.85"
```

```
line 5: syntax error, unrecognized character: `/'
line 5: syntax error, unexpected InvalidCharacter, expecting '"'
```

It declares a resistor which value is defined with an expression. This does not seem to be allowed by the parser. Other devices on the library use a Equ to precompute the values of components.

**Comment by ra3xdh** [comment]
Closed via #371
