### ISSUE TITLE
Should we use C++11 support?

### ISSUE THREAD

**Issue by ra3xdh** [Qucs/qucs#154]
Should we enable C++11? I have added C+11 support in CMakeLists and fixed some new warnings. It was quite easy. It seems, all works correct. You can see at sources at https://github.com/ra3xdh/qucs/tree/c++11 test branch. Qucs GUI and Qucs-activefilter are migrated to C++11. Build it using cmake build system to test C++11. Don't merge this branch!

**Comment by bastien-roucaries** [comment]
Ihave added to autoconf for qucs-core it is needed. It work like a charm and simplify code

**Comment by guitorri** [comment]
My only concern is about older systems. What is the default compiler on Debian stable? It might be harder to build for OSX older than 10.7. Anyway, it seems inevitable.

**Comment by yodalee** [comment]
Current Debian system is gcc 4.7.2. As this page said https://gcc.gnu.org/projects/cxx0x.html
I think most C++11 features are supported now.

**Comment by ra3xdh** [comment]
Also it's need to use MinGW version for Windows build that supports C++11. It seems MinGW4.7.2 supports it. We need be sure about our MinGW version.

**Comment by yodalee** [comment]
http://www.mingw.org/wiki/InstallationHOWTOforMinGW
I think it's gcc 4.8.1-4, see from the link.

**Comment by guitorri** [comment]
On Windows it should be fine. The easiest it to use a the compiler matching the official [Qt 4.8.6](http://download.qt.io/archive/qt/4.8/4.8.6/). Either MinGW 4.8.2 or VS2008/VS2010 (untested)

**Comment by ra3xdh** [comment]
Summarizing all above, we can use C+11. And I can continue with enabling С++11 support in GUI. It is already enabled at CMakeLists.txt of qucs-core.

**Comment by guitorri** [comment]
I guess it is easier to use CMake first on each Qt tool before bumping the top configure.ac. 
What about other compiler flags? Should we gradually increase the checks and strictness? Something along the lines reported in #52?

**Comment by ra3xdh** [comment]
I think `-Wall -Wextra` will be sufficient. Then we can increase warning level. Current `qucs-gui` build has about 20 remaining warnings. Some of them are explained in comments in code.

**Comment by ra3xdh** [comment]
Added `std=c++0x` to CMakeLists.txt of all qucs-tools. See https://github.com/ra3xdh/qucs/tree/c++11 . Also enabled warning level `-Wall` in all CMakeLists.txt. Where should I enable this option for `autotools` ?

**Comment by bastien-roucaries** [comment]
On Thu, Jan 8, 2015 at 5:00 PM, Vadim Kusnetsov <notifications@github.com>
wrote:

> Added std=c++0x to CMakeLists.txt of all qucs-tools. See
> https://github.com/ra3xdh/qucs/tree/c++11 . Also enabled warning level
> -Wall in all CMakeLists.txt. Where should I enable this option for
> autotools ?
>

For core it is not needed. I have done it.

Bastien

**Comment by ra3xdh** [comment]
@bastien-roucaries , I meant autotools build system of GUI

**Comment by guitorri** [comment]
@ra3xdh it should be somewhere inside this `case` logic: https://github.com/Qucs/qucs/blob/master/qucs/configure.ac#L225-L227

**Comment by guitorri** [comment]
@ra3xdh I am looking up the OSX build issue.

Shall we also move from `<math.h>` to `<cmath>` ? Maybe another PR.

**Comment by guitorri** [comment]
Merged.

**Comment by yodalee** [comment]
http://lists.qt-project.org/pipermail/development/2013-June/011310.html
We need to solve this, I suggest remove the warning.
