### ISSUE TITLE
Regression Qucsator

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#155]
After recent merges the example [qucs-test/testsuite/DC_TR_SW_spice_BFR520_prj](https://github.com/Qucs/qucs-test/tree/master/testsuite/DC_TR_SW_spice_BFR520_prj) started failing.

See logs below:

0.0.18 (debug mode), succeeds
https://gist.github.com/guitorri/a87a47194311ba133705

0.0.19 (after forguillem_cleanup_20141226 merge), failing
https://gist.github.com/guitorri/8c784618f012a17ecc14

Observations:
- internal component names are mangled (before / now)

   ```
   L:BFR520_cir.BFR520_1.X1.L1 _net1 BFR520_cir.BFR520_1.X1._net4 L="3.5e-10"
   L:BFR520_cir.BFR520_1..X1.L1 _net1 BFR520_cir.9?{?.X1._net4 L="3.5e-10"
   ```

- the last DC solutions are converging faster now.
- the TR is failing to start

**Comment by guitorri** [comment]
@bastien-roucaries can you take a took at it?

**Comment by bastien-roucaries** [comment]
It is commit c9694eb6595d767c55d76cb9416c2b633b8a4814 (by bissection)

**Comment by bastien-roucaries** [comment]
Sorry this is this one:
c49583263bdb4d98076c6a21fbf125c24dfe8516 is the first bad commit

commit c49583263bdb4d98076c6a21fbf125c24dfe8516
Author: Bastien ROUCARIÈS <roucaries.bastien@gmail.com>
Date:   Fri Dec 26 18:41:13 2014 +0100

    Use std::string for text concatenation in strlist

:040000 040000 8ca013259ecce883515587b5f143fd18ba10c5e1 6b2a4a2aa3360cdf3f7461a891a5a54fc93a27dc M      qucs-core

**Comment by bastien-roucaries** [comment]
Reverting work but it means that lifetime of object is not really clean and moreover it means massive leak...

Bastien

**Comment by guitorri** [comment]
Can you point to the leak? Did you run it with Valgrind?

**Comment by bastien-roucaries** [comment]
I run under valgrind. The goal of this patch was to clean lifetime of string... And it fail because code does not honor const contract.
