### ISSUE TITLE
Use of labels for the issue tracker.

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#166]
Perhaps we can discuss that?

What does the `A-qucs*` is supposed to mean? `A`ppplication ?

I find it a bit verbose. Can we just group type per color and have less text on the label? 

Like: [green] `qucs-gui`, [green] `qucs-filter`, ...,  [blue] `cmake`, [blue] `autotools` ....

**Comment by yodalee** [comment]
I did last night.
The mark started with `A` is the location of issue, and actually `A` means... nothing. I cannot figure out what prefix is better for this category.
I suggest a common prefix to same type of label, since they will appear together when we wanna add them. If word prefix like 'Mark', 'type' is verbose, maybe use single character, like prefix `A`, to be the prefix.

**Comment by guitorri** [comment]
I just renamed back to `question` and the labels already assigned went out of sync...
If you are prefixing just for the looks I find it unnecessary.
Anyway, we are doing the triage and we better know what label to use. The simple the better.
See these examples:
- https://github.com/JuliaLang/julia/labels
- https://github.com/scikit-learn/scikit-learn/labels

**Comment by yodalee** [comment]
It's not just issue of look. It's more clear that these tags, for example, 'platform-linux' 'platform-mac' appear together when people wanna add the tags. So they can mark the issue more quickly and precisely.
Anyway, the current arrangement is quite well to me. I will close this issue.

**Comment by guitorri** [comment]
Hold on! This is is not the way we should decide about it. What is good for *you* might not be good for others.

I dislike the current labels, I find it verbose, redundant and a pollution of the issues page. The tags end up being longer than the issue title which make them less readable.

**Comment by yodalee** [comment]
Well, I'm fine with this (of course orz)
I origin thought is add a common prefix to same group of tags, so adding tags will be more clear.
Imagine the old tags: doc, qucsator, qucs. Though they are in same color but they appear very far away.  I didn't know actually qucsator is talking about the "backend" of qucs until I search it.
Other tags group like "linux", "mac", "windows"; "autotool", "build", "CMake"; "bug", "enhancemenet", "refactor" encounter these problem too, not to mention they are in different color then.
If current version is too verbose, I suggest still keeps the prefix, at least one single character, so these tag will appear together in adding page.

**Comment by in3otd** [comment]
ok, I think I understood now what was the rationale behind the change. You would like to have labels which have the same color to be grouped together and not in alphabetical order, as GitHub orders them automatically currently.
But I needed to read your last message to get this (and I am not completely sure I understood correctly). You probably already know of the [Bike-shed effect] (http://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality) - on trivial things, everyone will feel compelled to express his opinion - so it would have been better to send a short message or open an issue before doing this, so at least we will have had everyone's opinion before.
Regarding the current labels, I didn't find anything wrong with the old ones and I do not see any actual improvement in the new ones.
[servo] (https://github.com/servo/servo) might have different needs, with currently 723 issues and 40 pull requests open. Maybe, when we will have similar numbers, we will all feel the need to change this :wink:
In any case, if the main problem is the label grouping, this is more a GitHub issue, and adding prefixes to labels is just a workaround; it will be better to ask GitHub for an enhancement (will never be done if no one asks for)

**Comment by guitorri** [comment]
This is my proposal for labels:

bug : add if confirmed
priority : if need quick fix (regression, severe bug)
easy-fix : small and well defined task, ideal for new contributor
documentation : qucs-doc directory, any documentation material
QEP : related to Qucs Enhancement Proposal
qucs-gui
qucs-activefilter
qucs-attenuator
qucs-doc
qucs-edit
qucs-filter
qucs-help
qucs-lib
qucs-rescodes
qucs-transcalc
qucsator
qucsconv
cmake
autotools
proposal
question
feature
windows
linux
osx

The 'confirmed', 'wont-fix', 'duplicate' are [unnecessary](http://www.ianbicking.org/blog/2014/03/use-github-issues-to-organize-a-project.html).
Just write down a comment or the link(#number) to the duplicate and close.

If an issue is a major feature or bug fix, also mark it in the milestone for the next release.
This will be helpful later on while writing the Release Notes (NEWS file)

Is it OK if I switch to the above labels?

**Comment by yodalee** [comment]
Only one opinion. I recommend group this label with color instead of colorful label. I prefer common prefix though, but this proposal is fine to me.

**Comment by guitorri** [comment]
Done. I tried to group a bit by color. Grouping labels is quite subjective, fell free to change the color if you like.
