### ISSUE TITLE
Lost `translations` history?

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#176]
Around commit 596d750b we moved the translations to `qucs/translations`. 
Am I missing something or the history of the files in it did not follow along. Is there a way to fix it?

**Comment by in3otd** [comment]
`git log --follow <filename>` still correctly shows a translation file history... found it googling around :smile: ; I didn't understand if not showing history for moved files in git is intentional, though.

**Comment by guitorri** [comment]
Thanks, sorry for the noise.
