### ISSUE TITLE
appVeyor seems having some error

### ISSUE THREAD

**Issue by yodalee** [Qucs/qucs#188]
I just push some new commit to the PR branch, and triggering Travis-CI and new CI appVeyor. The latter seems having an error on command line.
it clone the project with address:
`git clone -q git://github.com/Qucs/qucs.git C:\projects\qucs`
which should be:
`git@github.com:qucs/qucs.git`

**Comment by guitorri** [comment]
Sorry appVeyor was active by mistake... I am still experimenting to see how it works.

**Comment by guitorri** [comment]
I delete the AppVeyor project for now. I still have to figure out how to install Qt4 in there. They seem to have Qt5 only.

@yodalee, what do you mean by redefinition, that link is from a branch that Bastien is working on...

**Comment by yodalee** [comment]
My fault, no qucs-core error.
