### ISSUE TITLE
Copy/paste (and save/load) with 6 coupled inductors does not work

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#213]
There is a problem with the `N Mutual Inductors` component; using 6 coupled inductors the component is not pasted correctly after being copied (and not loaded correctly after being saved).
An example in [this schematic] (https://gist.github.com/in3otd/1f768b1cbd75efbb7f38); to "see" the bug, delete the mutual inductors component, instantiate a new one, change the number of inductors to 6 and then simulate: everything will work fine.
Now either
- "cut" the component (`Ctrl+X`) and then paste it
- or save the schematic, close it and then reopen it again

now the simulation will give wrong results.

If you make visible all the components properties you will see that after pasting the component (or reopening the file), the last inductance values are mixed up with the coupling coefficients...

**Comment by ra3xdh** [comment]
See #214 for fix.
