### ISSUE TITLE
Test netlist generation in qucs-test?

### ISSUE THREAD

**Issue by yodalee** [Qucs/qucs#220]
Follow issue #216 
To verify the function of netlist generation, could qucs-test be used to check the netlist generation?
Refer @guitorri

**Comment by guitorri** [comment]
Sorry, I did not see the reference to this issue.

In `qucs-test` there is some code to test `--qucs` (besides `--qucsator`).

It calls `qucs` in the command line to convert schematic to netlist, see https://github.com/Qucs/qucs/wiki/Qucs-Command-Line-Tools

I haven't tested it much. I also noticed that when an old schematic is loaded on the GUI and saved again, during the save the schematic is updated to the latest list of properties. Hence the number of properties might be updated. So, depending on how you convert to netlist (manually or command line) it might be different.

I won't have time to loop it up.
