### ISSUE TITLE
Data display tab shows .sch extension instead of .dpl

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#229]
when you simulate a schematic, the corresponding Data Display tab opened at the end of the simulation shows an extension .sch instead of .dpl (but is correctly saved as .dpl)...

**Comment by yodalee** [comment]
https://github.com/Qucs/qucs/blob/master/qucs/qucs/qucs.cpp#L2123
`Info.fileName()` should be `Name`, also line num 2127 has same problem.
