### ISSUE TITLE
Stale Include?

### ISSUE THREAD

**Issue by nvdl** [Qucs/qucs#270]
In "searchdialog.cpp"
#include "ui_searchdialog.h"

Is it a stale include?

**Comment by guitorri** [comment]
This should come from https://github.com/Qucs/qucs/blob/master/qucs/qucs/dialogs/searchdialog.ui
This is the only dialog created in this format. After this was merged we decided to keep the dialogs coded by hand instead of investing time on converting them to the UI designer.

**Comment by nvdl** [comment]
Was getting compilation error.

"ui_searchdialog.h" was empty on my side.
Do not know how it ended up like that.

Fixed by copying the file from master branch.
