### ISSUE TITLE
Space character in project name breaks table creation after digital simulation

### ISSUE THREAD

**Issue by fer-rum** [Qucs/qucs#28]
Having a space character in the name of the project prevents digital simulation from completing.
### Steps to reproduce:
- create a project with a name containing a space e.g. _Full Adder_
- create a digital circuit in the project
- do a digital simulation of the circuit
- attempt to show simulation results as a truth table

The last step fails. When running the created simulation, the simulator
is fine. It can be run from command line and it simulates the circuit
as expected.
Within qucs however, One can not add a truth table, one gets no choice of
signals to add to it. 
No warnings or error messages are shown.
However, a file _Full_ that contains the missing truth table will be created.

---

The issue seems to be fixed if the commands are quoted before calling the `qucsdigi` and `qucsveri`:
- [x] Fix `qucsdigi`, `qucsveri` on Linux, OSX.  https://github.com/Qucs/qucs/pull/64
- [ ] Fix/Test `qucsdigilib`  on Linux, OSX
- [ ] Fixes on Windows

**Comment by yodalee** [comment]
Anything new to this?

**Comment by nouwaarom** [comment]
Also having a whitespace in a schematic name causes ngspice to fail the simulation on the rebase_spice4qucs branch.

I think this is because in the netlist there is a *write* command followed by a filename which is based on the schematic name. Ngspice doesnt understand the filename if it contains spaces and throws an error.

**Comment by ra3xdh** [comment]
@nouwaarom , I have enabled spaces in schematic name with Ngspice simulations. See the latest commit on `rebase_spice4qucs` branch. This commit should fix this.

**Comment by nouwaarom** [comment]
@ra3xdh, Thank you, now it works fine
