### ISSUE TITLE
Component dialog move up/down fail to move row.

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#319]
The move up/down on a Equation component only move items on the first column. It should move the complete row.

This messes up the left-hand-side and right-hand-side of the equations.

![snap 2015-07-20 at 11 22 11](https://cloud.githubusercontent.com/assets/1388949/8773337/c17173fc-2ed3-11e5-8d7c-28f97a0cf3fc.png)
![snap 2015-07-20 at 11 22 25](https://cloud.githubusercontent.com/assets/1388949/8773338/c173b7fc-2ed3-11e5-9992-3cda70b4ef9d.png)

**Comment by felix-salfelder** [comment]
is there any indication that this is related to the marker move cleanup? or am i just being paranoid?

**Comment by guitorri** [comment]
:smile: Don't worry... this is related to `componentdialog`, the `slotButtUp` and `slotButtDown` to be specific.
Several dialogs had to be tweaked/ported to fit with Qt4, bugs were introduced in the process I think I was the last to mess with this dialog... I opened the ticked so we don't forget about it.

**Comment by in3otd** [comment]
yep, as guitorri said, I've just checked, it was broken even before the marker move cleanup. (I did not have the time to bisect to find out the bad commit). So you can relax :smile:

**Comment by guitorri** [comment]
I will take the blame on this again... 84f51e42

**Comment by ra3xdh** [comment]
See #324 for fix
