### ISSUE TITLE
MAINTAINER_MODE

### ISSUE THREAD

**Issue by felix-salfelder** [Qucs/qucs#360]
we should get rid of this (=always enable). i cannot see a use case, and the build without MAINTAINER_MODE enabled seems broken. does somebody really use this "magic"?

fwiw: I am not hallucinating, even the MAINTAINER_MODE author himself has been convinced against (citing the manual).

**Comment by guitorri** [comment]
You are not hallucinating. It should be dropped. :)

**Comment by felix-salfelder** [comment]
OK. i have taken care of this between the lines of the distcheck PRs.
