### ISSUE TITLE
LM317 models not working as expected 

### ISSUE THREAD

**Issue by ntavish** [Qucs/qucs#367]
![Vin sweep](http://i.imgur.com/FFv6Xmt.png)
Vout should be 2.5V, and it should settle above around Vin=5V

Parameter sweep on R2, with constant Vin also is not at all as expected.

**Comment by guitorri** [comment]
Can you put the schematic into a Gist, or somewhere we can have a look a it?

**Comment by ntavish** [comment]
https://gist.github.com/ntavish/952c281f78be632c9f7a

This isn't on the same computer, and probably an older version(0.0.15-1.1 version for ubuntu 12.04), but result is the same.

**Comment by ra3xdh** [comment]
I think it is bug on Qucs-library side. There are two models for LM317 in Qucs library. LM317K-2 is working as expected (2.5 V at output), LM317K-1 and LM337 give wrong result. @ntavish , You can use LM317K-2 to get proper result.
![lm317](https://cloud.githubusercontent.com/assets/4920080/9959718/baeb38c2-5e1e-11e5-9d9f-a0091c6a74f8.png)

**Comment by in3otd** [comment]
looking at the component netlist I have the impression that the ADJ and OUT connection were swapped; indeed when swapping them on the schematic the output voltage seems correct.

**Comment by in3otd** [comment]
BTW @ra3xdh , the LM3**3**7 is a *negative* voltage regulator, if you apply -12 V at its input it works as expected.

**Comment by ra3xdh** [comment]
Closed via #375.
