### ISSUE TITLE
bug in qucs-gui

### ISSUE THREAD

**Issue by felix-salfelder** [Qucs/qucs#385]
- start qucs-gui (`qucs`)
- on the left, select "Components", then left click "Resistor"
- move mouse cursor to drawing area, click (place)
- hit escape key (regain normal mouse)
- left click just placed resistor (select)
- ctrl+c, ctrl+v opens error window "Format Error. Wrong line start".

**Comment by in3otd** [comment]
uhm... cannot reproduce here... Qucs 0.0.19 from the current master with Linux...
are there any other steps  in between? the final ctrl+v places a resistor on the cursor, as expected.

**Comment by felix-salfelder** [comment]
i must have mixed up a have baked patch with my master branch. it's working again.

sorry for wasting your time. `:|`
