### ISSUE TITLE
OpAmp model from Ideal library don't work

### ISSUE THREAD

**Issue by stranger573** [Qucs/qucs#404]
OpAmp model from Ideal library contains errors. Attached patch is repair this.
[patch.zip](https://github.com/Qucs/qucs/files/55616/patch.zip)

**Comment by ra3xdh** [comment]
@stranger573 Are you using 0.0.18? This was fixed in 0.0.19. See #140 and #371 for fix. Please test `Ideal.lib` from 0.0.19.

**Comment by stranger573** [comment]
My patch for qucs-0.0.19-150523-git-0046130 Ideal library. More new this exists?

**Comment by stranger573** [comment]
Yes. In master branch this OK.
