### ISSUE TITLE
IRC #qucs is empty

### ISSUE THREAD

**Issue by Symbian9** [Qucs/qucs#410]
As you sad on https://github.com/Qucs/qucs/wiki/Submitting-Issues page
<code># qucs IRC channel on chat.freenode.net are better places to get help.</code>
But for now this channel is empty. Did you register it?

**Comment by andresmmera** [comment]
It seems that the IRC channel is usually empty... In any case, you can report issues or simply find help at qucs-help mailing list (http://sourceforge.net/p/qucs/mailman/qucs-help/)

**Comment by in3otd** [comment]
...yep, I guess it's the usual "chicken and egg" problem; since the `#qucs` channel is rarely used people feel not encouraged to use it.

FYI, I have just joined after quite some time and was pleasantly surprised to find another use already there, so let's try to use #qucs more :grin:

**Comment by guitorri** [comment]
I registered the #qucs and ##qucs channels at freenode back in Jan 2015. 
I will try to use it while I am doing something Qucs related.
If anyone wants to become an operator please let me know.

**Comment by guitorri** [comment]
We are there... from time to time... I will try to put a topic on the channel.
