### ISSUE TITLE
qucs-rescodes issues

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#445]
- [x] the menu is not extending
 - [x] it does not changes the font, when changed in the Qucs settings.
 - [ ] the about dialog could state a correct reference to the license

![image](https://cloud.githubusercontent.com/assets/1388949/12855491/08e8fde0-cc40-11e5-9c15-8fb36f49091a.png)

**Comment by in3otd** [comment]
yep, saw some time ago that this little tool was different, I think I may have already the first point done somewhere.
Regarding the "correct reference to the license", the text is the "standard" blurb used by the other tools, should we update all of them , then? I cannot find a reference for this exact text in the GPL, but googling it seems to be used in may other SW, e.g. https://www.gnu.org/software/help2man/

**Comment by in3otd** [comment]
fixed the first two points, please advise about the third

**Comment by guitorri** [comment]
hum... either nothing or something like:

```
Qucs-rescodes is part of the Qucs project.

Qucs is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option) any later version.

This software is distributed in the hope that it will be useful,but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details..

You should have received a copy of the GNU General Public License along with Qucs, see the file COPYING. If not see http://www.gnu.org/licenses/ or write to the Free Software Foundation, Inc., 51 Franklin Street - Fifth Floor,Boston, MA 02110-1301, USA.
```

**Comment by guitorri** [comment]
Or the stardard text from http://www.gnu.org/licenses/gpl-2.0.html
