### ISSUE TITLE
Set windows icons in OS X ?

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#450]
While looking at the code of `qucsrescodes` I saw it does not set the windows icon when `__APPLE__` is defined (see [here] (https://github.com/Qucs/qucs/blob/master/qucs/qucs-rescodes/main.cpp#L54-L57)), while other tools, like `qucstrans`, set it in every case (see [here] (https://github.com/Qucs/qucs/blob/master/qucs/qucs-transcalc/qucstrans.cpp#L257-L258)).
Does this make a difference? I do not have a Mac, so I have no idea...

**Comment by guitorri** [comment]
There is no window icon on OSX. At best you get an icon on the dock. But for that the icon gets assigned when application is bundled... I don't think it makes any difference.

**Comment by in3otd** [comment]
ok, so if you see no difference between e.g. `qucsrescodes` and `qucstrans` we can safely remove the `#ifndef __APPLE__` around `setWindowIcon()`
