### ISSUE TITLE
x-axis scaling error in spice4qucs version of program under win7/10

### ISSUE THREAD

**Issue by r2com** [Qucs/qucs#505]
Some plot was generated, when i decided to put manual start/stop and step the assertion dialog popped up. Screenshot attached.

![image](https://cloud.githubusercontent.com/assets/18331178/14395148/0c342404-fd9e-11e5-9059-d68b1ac6aa16.png)

**Comment by ra3xdh** [comment]
Fixed in upstream code by #313 . The latest release candidate 0.0.19S-rc6 contains this fix.
