### ISSUE TITLE
Exported graph image has the markers cut

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#522]
a little thing, that I find somewhat annoying:
select a graph with markers, then export it as image (`File` -> `Export as image` then check `Export selected only`): the exported image is sized to fit the graph only, but the marker lines are visible.

Either we should:
-  not show the markers at all (not nice), or
- size the exported image to include the graphs (good), or
- allow the user to choose (even better).

Example:
- exported image with cropped markers (current behaviour)
  ![exported_graph_ko](https://cloud.githubusercontent.com/assets/9018179/15992548/235fc228-30cf-11e6-86e3-cf8526780f66.png)
- exported image as it should be
  ![exported_graph_ok](https://cloud.githubusercontent.com/assets/9018179/15992551/3496c348-30cf-11e6-8c73-53dd6749e099.png)

**Comment by ra3xdh** [comment]
I confirm this issue. There also exists similar issue with wire labels. I will add fix soon. It's strange that I never met it before. I often use export of diagrams and schematics to images for articles preparation.

**Comment by ra3xdh** [comment]
@in3otd, See #523 for fix.

**Comment by guitorri** [comment]
Fixed with #523.
