### ISSUE TITLE
Equation component: Incorrect Property name when using Enter to accept edit

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#526]
while checking #514 I noticed a bizarre behaviour of the Equation component:
- place an Equation component on the schematic
- double click the Equation to open its Edit Properties dialog
- the selection is now on the first Line Edit (the Name of the property): type something (e.g. *Name*)
- press **Tab** to move to the second Line Edit (the Value of the property): type something (e.g. *Value*)
- press **Enter** to save the modified property...
- now the modified property shows up with name=***Value*** and Value=*Value*... the entered *Name* has disappeared. :confused: 

I'll take a look...

**Comment by ra3xdh** [comment]
Fixed via #527
