### ISSUE TITLE
Strange behavior of the cursor when in "Wire placement" mode

### ISSUE THREAD

**Issue by pidgeon777** [Qucs/qucs#540]
This problem arises when I select the "Wire placement" mode (CTRL+E), zooming in and out. Let's suppose I start with the whole schematic displayed (press "0"):

![image](https://cloud.githubusercontent.com/assets/13739892/16751049/b74c3098-47d6-11e6-953f-d1fccb622bc6.png)

then I decide to zoom in:

![image](https://cloud.githubusercontent.com/assets/13739892/16751058/cd361c34-47d6-11e6-99e4-37ab7dd51147.png)

zoom again:

![image](https://cloud.githubusercontent.com/assets/13739892/16751065/da98947e-47d6-11e6-8b97-325b64e8d01f.png)

and again:

![image](https://cloud.githubusercontent.com/assets/13739892/16751076/f6e21664-47d6-11e6-936c-7e38252a2e11.png)

You see how the two lines (vertical and horizontal) which marks the cursor, doesn't cross anymore, after a certain amount of zoom. I tried this in the "Wire placement" mode (CTRL+E). When zooming out, the two lines will eventually cross again.

I'm using Qucs v0.0.19 (qucs-win64-bin portable version), running it on a Windows 7 x64 machine, resolution is 1920x1080.

**Comment by in3otd** [comment]
this appears to be the issues solved by #504... seems ready to be merged...

**Comment by guitorri** [comment]
Should be fixed with #504
