### ISSUE TITLE
component library can't load lib files on windows

### ISSUE THREAD

**Issue by aviadb** [Qucs/qucs#542]
when launching component library
an error message is displayed

`
Cannot open "/c/qucs-win64-bin/share/qucs/library/.lib
`

The component library then opened empty without any libraries loaded

**Comment by pidgeon777** [comment]
I confirm the same problem:

![image](https://cloud.githubusercontent.com/assets/13739892/16773076/d42ee3f6-4856-11e6-93d5-de6cb9bf25c1.png)

![image](https://cloud.githubusercontent.com/assets/13739892/16773092/e39de6d4-4856-11e6-8878-eb5e6b8e4c75.png)

![image](https://cloud.githubusercontent.com/assets/13739892/16773104/ec7380d4-4856-11e6-94ab-cdf82e490458.png)

I'm using Qucs v0.0.19 (qucs-win64-bin portable version), running it on a Windows 7 x64 machine.

**Comment by pidgeon777** [comment]
This is weird. I've set Qucs language to Italian, and the software rightly starts in Italian when opened directly in Windows (i.e. double click on "qucs.exe"). Anyway, if I open Qucs through the command window as you suggested, the program runs in English.

About your suggestion, trying with:

`set QUCSDIR=c:\qucs-win64-bin\bin`

leads to this, when launching component library:

![image](https://cloud.githubusercontent.com/assets/13739892/16862777/dc9efbfa-4a4c-11e6-84a6-ff02357941d7.png)

It seems that the correct command would be:

`set QUCSDIR=c:\qucs-win64-bin`

leading to the proper result:

![image](https://cloud.githubusercontent.com/assets/13739892/16862786/e929da98-4a4c-11e6-9a34-304060bfc8a9.png)

**Comment by in3otd** [comment]
thanks; I didn't actually try and had the feeling it may not have been fully right.

Regarding the language issue you mentioned, on the command line it uses English regardless if you set the `QUCSDIR` variable or not? I think that if Qucs cannot find the language translation files it defaults to English.

We had quite some issues with the various components paths in the past, #501 mentions it also fixed some problems with the translations.

**Comment by pidgeon777** [comment]
Hi in3otd, what do you exactly mean with checking if on the command line it uses English? This is what I did:

1) Start a cmd session.
2) cd C:\Users\XXX\Desktop\qucs-win64-bin\bin
3) qucs

Anyway, I just tried again, and this time Qucs started in Italian. Then I decided to set it in English, and I started it again through the cmd window. It ran in English. Then I set it in Italian one last time, and it run in Italian. So, it seems that currently the problem doesn't arise anymore.

**Comment by in3otd** [comment]
I meant to say/write "starting it from the command line does it use English regardless if you set the `QUCSDIR` variable or not?", so you did it correctly.

 I'll try to see if I can reproduce the issue here...

**Comment by felix-salfelder** [comment]
> So, it seems that currently the problem doesn't arise anymore.

closing. please reopen as needed.
