### ISSUE TITLE
Component search selects wrong MOS component

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#543]
Steps to reproduce (in `release-0.0.19` and older):
- select the Components tab in the Main Dock on the left side
- type `MOS` in the search box at the bottom: eight MOS symbols will appear
- select the first symbol (`n-MOSFET`) and place it on the schematic
- note that the symbol placed is not the one for the standard `n-MOSFET` just selected but the one for the `n-MOSFET with substrate`. (the two have the same description in the Components tab, maybe not a coincidence...)

(similar issue exists with the `p-MOSFET`)

**Comment by guitorri** [comment]
Fixed by #549
