### ISSUE TITLE
Bad components preview in "Qucs Library Tool 0.0.19"

### ISSUE THREAD

**Issue by pidgeon777** [Qucs/qucs#550]
When selecting a component in the Qucs Library Tool window, sometimes the preview of the component is wrong.
Steps to reproduce the problem:

1) Tools -> Component Library (CTRL + 5).

![image](https://cloud.githubusercontent.com/assets/13739892/17084447/4d2d7e14-51be-11e6-8188-31e860be031a.png)

2) Digit "741" (with no quotes) in the search box, and select the first result.

![image](https://cloud.githubusercontent.com/assets/13739892/17084452/7937223a-51be-11e6-8e6f-cd2d8f6dda72.png)

3) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084455/9e47d448-51be-11e6-894f-dc81620dfd01.png)

4) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084457/a7acf6a8-51be-11e6-8daf-db11b2af6446.png)

5) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084459/adcf0288-51be-11e6-82c3-2de5e2e1929c.png)

6) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084460/b3407832-51be-11e6-916b-c1c906bee79e.png)

7) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084461/b96a8496-51be-11e6-92b1-ccf712717716.png)

8) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084464/bf6e7ec4-51be-11e6-80bb-91e7a9d71a77.png)

9) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084465/c35ab926-51be-11e6-99aa-357c1e339001.png)

10) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084467/c97fe6a0-51be-11e6-846f-8be60c4d4ebd.png)

11) Press arrow down in the keyboard.

![image](https://cloud.githubusercontent.com/assets/13739892/17084468/d057fc9c-51be-11e6-8e66-d4997d55bbf6.png)

You can notice how, in many cases, the preview of the selected component is wrong.
I'm using Qucs v0.0.19 (qucs-win64-bin portable version), running it on a Windows 7 x64 machine.

**Comment by in3otd** [comment]
this is almost surely related to #543... I did port the search code from the GUI to the Library Tool...

**Comment by andresmmera** [comment]
I reckon that #556 solves the problem. Just for checking, could you test it?

**Comment by guitorri** [comment]
Fix merged with #580.
