### ISSUE TITLE
Simple DC sweep from tutorial creates strange plots.

### ISSUE THREAD

**Issue by JohnCC330** [Qucs/qucs#551]
I'm a new user to QUCS, and after the simple voltage divider, I hit the wall with the second tutorial (DC sweep of transistor parameters). I tried to enter the components as in the tutorial, but get strange results, as can be seen in the screenshot attached (also attached the circuit file, and a screenshot of same).
I find the plots rather intriguing - No idea where those pulses come from!
(My apologies for posting this as an issue, I couldn't find how to do attachments on Sourceforge)

BTW, this is QUCS 0.0.18 on Linux. I get *loads* of warnings in the log, but from googling them I suspect they don't indicate problems (added the zipped log too).

![screenshot_2016-07-29_00-47-41](https://cloud.githubusercontent.com/assets/3728987/17237878/e1420a5e-552c-11e6-9102-576f220c31cb.png)
![screenshot_2016-07-29_02-05-48](https://cloud.githubusercontent.com/assets/3728987/17238321/1bfe1f30-5531-11e6-8fee-2fedf2871015.png)
[transistor_dc.sch.gz](https://github.com/Qucs/qucs/files/389881/transistor_dc.sch.gz)
[log.txt.gz](https://github.com/Qucs/qucs/files/389909/log.txt.gz)

**Comment by JohnCC330** [comment]
Ok... Not my best moment - Ground was missing. Still strange these signals appeared, isn't it?

**Comment by andresmmera** [comment]
Hello John, 

Maybe too late,... but I usually employ [this schematic](https://dl.dropboxusercontent.com/u/21294824/BJT_StaticIV.sch) as BJT curve tracer.

Hope it helps :-)

**Comment by JohnCC330** [comment]
Thanks Andrés. Yes, I had solved the problem, as I said in my previous mail, by adding a Gnd connection to the circuit. Your circuit works great, but I rather prefer to change Vce logarithmically - it gives much more information in the lower range, where the non-linear events are. Gracias!
![screenshot_2016-08-01_10-55-45](https://cloud.githubusercontent.com/assets/3728987/17296321/fd70c0a6-57d6-11e6-81dd-3bfb3c572159.png)
