### ISSUE TITLE
Search lib components tool doesn't place the proper component

### ISSUE THREAD

**Issue by andresmmera** [Qucs/qucs#553]
Hello, 

I've found a problem with the component library tool... It doesn't place the right part after using the searchbox. 

Steps to reproduce (OS: Fedora 24):
i) Open the component library tool (CTRL+5)
ii) Search a part. For example, select the NMOSFET tab and type IRF510 in the search line.
iii) Select the part on the list and then press the "Copy to clipboard" button.
iv) Paste the component into a schematic. Then go to the component properties (Double click) and you'll see that the name of the component is 2N3796.

I'll try to take a look to the code.

![selection_008](https://cloud.githubusercontent.com/assets/13180689/17568305/7b65a22e-5f43-11e6-80db-0493a20a0802.png)
![selection_009](https://cloud.githubusercontent.com/assets/13180689/17568306/7b6c4d72-5f43-11e6-908f-bc9a6c6fad04.png)

**Comment by in3otd** [comment]
may be the same as #550 ...

**Comment by andresmmera** [comment]
Yes,... I didn't check previous issues :S
