### ISSUE TITLE
ngspice/ac.v(vin)  vs.  vin.v   requires change of diagram when changing simulator

### ISSUE THREAD

**Issue by ldpgh** [Qucs/qucs#565]
When I change the simulator from Qucsator to Ngspcie and back the naming convention of the data requires to modified the diagram. It's a difficult task (from a verification standpoint) if the testbench need to be touched for every simulator change.

**Comment by ra3xdh** [comment]
This was discussed somewhere at #77 . And we lead to conclusion to preserve SPICE notation in output variables naming. You can have two diagrams: one for SPICE and open for Qucsator. Or put data into one diagram. This point will not be changed.  Also such behavior allows to have datasets form all simulator simultaneously. It allows to switch between datasets and compare results between simulators.
