### ISSUE TITLE
Out-off-tree build, configure cannot find QTABWIDGET_SETMOVABLE check.

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#576]
To reproduce:
```
cd ~/git/qucs && ./bootstrap
cd ~/git/build-off-tree && ../qucs/configure
```
At some point:
```
../../qucs/qucs/configure: line 7335: QUCS_CHECK_FUNC_QTABWIDGET_SETMOVABLE: command not found
```

**Comment by in3otd** [comment]
uhm, cannot reproduce here. 

`automake` version? Here `automake (GNU automake) 1.15`

**Comment by guitorri** [comment]
Thank you for checking and sorry for waisting your time. I cannot reproduce either. The issue disappeared...
