### ISSUE TITLE
Export as image, timing diagram text shifted up.

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#578]
Spotted this while testing #523.

See exported image below. Note the text shifted up in the timing diagram :
![export](https://cloud.githubusercontent.com/assets/1388949/19932319/f91b3c8e-a10f-11e6-9043-b1a01dd983bd.png)

The project is here: [05-verilog_counter_prj.zip](https://github.com/Qucs/qucs/files/566768/05-verilog_counter_prj.zip)

**Comment by in3otd** [comment]
uhm, this seems to have appeared with c9fcce60b1ddcefcc425a6c909ef6914ccb02a98 but I don't understand why...

Another small printing issue is that when printing from the command line the text painting (in blue above) is cut (but not when printing from the GUI)

**Comment by ra3xdh** [comment]
There may exist not obvious connection between Marker and Timing diagrams. But I don't understand how they may be connected too. I will try to dig into legacy code in the next few days.

**Comment by guitorri** [comment]
in3otd have you checked before and after c9fcce6. I was pretty sure I did not include it when I reported. I will check again.

**Comment by in3otd** [comment]
yes, I've checked before and after, did `make distclean` in between but I cannot exclude a mistake :grin:

**Comment by in3otd** [comment]
ok, it's clearer now: we are [now](https://github.com/Qucs/qucs/commit/c9fcce60b1ddcefcc425a6c909ef6914ccb02a98#diff-12763b2bbd1d04ec7aa8054d6f637f86R710)  calling `paintDiagram()` to paint every diagram while we should actually call `paint()`, as done before.
`paintDiagram()` is the method of the `Diagram()` base class, while the timing diagram is a `TabDiagram()` (a child of `Diagram()`) and we need to use its own `paint()` method (which also prints the Tab Diagram scrollbar, which is now missing) to have it printed correctly.
Something needs to be modified to have the marker print stuff working as expected now...
