### ISSUE TITLE
NGSPICE Netlist Issue (spice4qucs_current)

### ISSUE THREAD

**Issue by nvdl** [Qucs/qucs#602]
Netlisting for switches W(CSW) is not fully functional.

For example:
`W6 WL1_1  _net3 W7 _net4  _net5 W8 _net6  _net7 W9 _net8  BL0 W10 _net9  BL1 W11 _net10  BL2 W12 _net11  BL3 W13 _net12  BL4 R47 WL0 WL0_1  2K`

Here R47 showed up with switch definition.

Don't know the status of this branch for this component though.

@ra3xdh?

**Comment by ra3xdh** [comment]
There is no bug. Switch works as expected. You are using empty parameters for switch. You should use the full switch SPICE definition as the parameter (see Ngspice manual for details). See attached example circuit.
![wsw](https://cloud.githubusercontent.com/assets/4920080/20304552/539fed46-ab4a-11e6-9d8b-ebd75be83ecf.png)
