### ISSUE TITLE
Paintings could not be added into subcircuit symbols

### ISSUE THREAD

**Issue by ra3xdh** [Qucs/qucs#629]
I have found a bug that can stop release preparation. Steps to reproduce:

* Open schematic, containing subcircuit symbol
* Switch to subcircuit symbol mode (F9)
* Try to add a painting.  Circuit components will be added instead. 

Attached screenshot shows what happen:
![subcir_bug](https://cloud.githubusercontent.com/assets/4920080/20878278/7db13a70-bae7-11e6-93c1-30659ee1161d.png)

**Comment by in3otd** [comment]
I think I know where this comes from, I'll try to push a fix today

**Comment by ra3xdh** [comment]
Fixed by #630
