### ISSUE TITLE
Equation replace depend source

### ISSUE THREAD

**Issue by z-Wind** [Qucs/qucs#650]
OS : window7x64
version : 0.0.19

Hi
I know there is a source, "voltage controlled voltage source".
However, when I try to replace it by equation like "V1=2 * Vx.V", the dc simulation is wrong as shown.
And V1.I=0 A, but V1.V=26.7V. It seems odd.

![test](https://cloud.githubusercontent.com/assets/16359142/22402372/d2c3be20-e62f-11e6-9f67-d3ab90c0f7a7.jpg)

**Comment by ra3xdh** [comment]
As far as I know, such combination may be not supported. Use Equation defined device (EDD) instead. EDD is what you need. This manual explains how to use EDDs: http://qucs.sourceforge.net/docs/tutorial/equations.pdf
