### ISSUE TITLE
Permission request for add localization for Chinese

### ISSUE THREAD

**Issue by Towdium** [Qucs/qucs#709]
Hi,
I have sent join request on transifex website and there has been no update for few weeks, so I think it could be helpful if I open an issue here. Long story short, I'm a year 3 eee undergraduate student at the UK and my first language is Chinese. I have been using qucs for several months. Since most of strings are missing localization in Chinsese, I think I can provide some help in for basic components and interface texts. I hope my request can be passed so that I can help.

**Comment by guitorri** [comment]
For some reason I did not receive your request. I just accepted your request. Thank you for joining!

**Comment by Towdium** [comment]
That's great!
