### ISSUE TITLE
qucs-0.0.19 fails to build - configure failed while checking for Qt library

### ISSUE THREAD

**Issue by 1greyghost** [Qucs/qucs#711]
(This is on a new install of Linux Mint 18.2)

I did the following: 

ADMS
- downloaded and unpacked adms-2.3.6
- sudo apt-get install build-essential
- sudo apt-get install automake libtool gperf flex bison
- sudo apt-get install libxml2 libxml2-dev
- sudo apt-get install libgd-perl
- sudo sh bootstrap.sh
- sudo ./configure --enable-maintainer-mode
- sudo make install

Great adms made!!

QUCS
- downloaded and unpacked qucs
- sudo apt-get install libqt4-dev libqt4-qt3support
- sudo apt-get install texlive-font-utils octave-epstk
- installed qt4-dev-tools via synaptic 
- sudo ./configure

Bummer, the configure failed.  below are the last few lines of the configure process:

    checking for X... no
    checking for Qt headers... found in /usr/include/qt4 -I/usr/include/qt4/Qt -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtScript -I/usr/include/qt4/Qt3Support
    checking for Qt... 4 (multi-threaded)
    checking for Qt library... configure: error: not found
    configure: error: ./configure failed for qucs

Any thoughts?

**Comment by felix-salfelder** [comment]
checking for X... no

looks strange to me. no X on Mint?

    checking for Qt library... configure: error: not found

so you did instal some Qt libraries? which/how?
configure should have written more details to config.log,  can you show us the relevant chunk?

**Comment by 1greyghost** [comment]
felix, below is the config.log:

This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by qucs configure 0.0.19, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  $ ./configure 

## --------- ##
## Platform. ##
## --------- ##

hostname = Elfworks
uname -m = x86_64
uname -r = 4.10.0-33-generic
uname -s = Linux
uname -v = #37~16.04.1-Ubuntu SMP Fri Aug 11 14:07:24 UTC 2017

/usr/bin/uname -p = unknown
/bin/uname -X     = unknown

/bin/arch              = unknown
/usr/bin/arch -k       = unknown
/usr/convex/getsysinfo = unknown
/usr/bin/hostinfo      = unknown
/bin/machine           = unknown
/usr/bin/oslevel       = unknown
/bin/universe          = unknown

PATH: /usr/local/sbin
PATH: /usr/local/bin
PATH: /usr/sbin
PATH: /usr/bin
PATH: /sbin
PATH: /bin
PATH: /snap/bin


## ----------- ##
## Core tests. ##
## ----------- ##

configure:1904: checking build system type
configure:1918: result: x86_64-unknown-linux-gnu
configure:1938: checking host system type
configure:1951: result: x86_64-unknown-linux-gnu
configure:1988: checking for a BSD-compatible install
configure:2056: result: /usr/bin/install -c
configure:2067: checking whether build environment is sane
configure:2122: result: yes
configure:2273: checking for a thread-safe mkdir -p
configure:2312: result: /bin/mkdir -p
configure:2319: checking for gawk
configure:2335: found /usr/bin/gawk
configure:2346: result: gawk
configure:2357: checking whether make sets $(MAKE)
configure:2379: result: yes
configure:2408: checking whether make supports nested variables
configure:2425: result: yes
configure:2611: checking for g++
configure:2627: found /usr/bin/g++
configure:2638: result: g++
configure:2665: checking for C++ compiler version
configure:2674: g++ --version >&5
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:2685: $? = 0
configure:2674: g++ -v >&5
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
configure:2685: $? = 0
configure:2674: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:2685: $? = 1
configure:2674: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'
g++: fatal error: no input files
compilation terminated.
configure:2685: $? = 1
configure:2705: checking whether the C++ compiler works
configure:2727: g++    conftest.cpp  >&5
configure:2731: $? = 0
configure:2779: result: yes
configure:2782: checking for C++ compiler default output file name
configure:2784: result: a.out
configure:2790: checking for suffix of executables
configure:2797: g++ -o conftest    conftest.cpp  >&5
configure:2801: $? = 0
configure:2823: result: 
configure:2845: checking whether we are cross compiling
configure:2853: g++ -o conftest    conftest.cpp  >&5
configure:2857: $? = 0
configure:2864: ./conftest
configure:2868: $? = 0
configure:2883: result: no
configure:2888: checking for suffix of object files
configure:2910: g++ -c   conftest.cpp >&5
configure:2914: $? = 0
configure:2935: result: o
configure:2939: checking whether we are using the GNU C++ compiler
configure:2958: g++ -c   conftest.cpp >&5
configure:2958: $? = 0
configure:2967: result: yes
configure:2976: checking whether g++ accepts -g
configure:2996: g++ -c -g  conftest.cpp >&5
configure:2996: $? = 0
configure:3037: result: yes
configure:3071: checking for style of include used by make
configure:3099: result: GNU
configure:3125: checking dependency style of g++
configure:3236: result: none
configure:3299: checking for gcc
configure:3315: found /usr/bin/gcc
configure:3326: result: gcc
configure:3555: checking for C compiler version
configure:3564: gcc --version >&5
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

configure:3575: $? = 0
configure:3564: gcc -v >&5
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.4.0-6ubuntu1~16.04.4' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4) 
configure:3575: $? = 0
configure:3564: gcc -V >&5
gcc: error: unrecognized command line option '-V'
gcc: fatal error: no input files
compilation terminated.
configure:3575: $? = 1
configure:3564: gcc -qversion >&5
gcc: error: unrecognized command line option '-qversion'
gcc: fatal error: no input files
compilation terminated.
configure:3575: $? = 1
configure:3579: checking whether we are using the GNU C compiler
configure:3598: gcc -c   conftest.c >&5
configure:3598: $? = 0
configure:3607: result: yes
configure:3616: checking whether gcc accepts -g
configure:3636: gcc -c -g  conftest.c >&5
configure:3636: $? = 0
configure:3677: result: yes
configure:3694: checking for gcc option to accept ISO C89
configure:3757: gcc  -c -g -O2  conftest.c >&5
configure:3757: $? = 0
configure:3770: result: none needed
configure:3795: checking whether gcc understands -c and -o together
configure:3817: gcc -c conftest.c -o conftest2.o
configure:3820: $? = 0
configure:3817: gcc -c conftest.c -o conftest2.o
configure:3820: $? = 0
configure:3832: result: yes
configure:3851: checking dependency style of gcc
configure:3962: result: none
configure:4184: checking that generated files are newer than configure
configure:4190: result: done
configure:4229: creating ./config.status

## ---------------------- ##
## Running config.status. ##
## ---------------------- ##

This file was extended by qucs config.status 0.0.19, which was
generated by GNU Autoconf 2.69.  Invocation command line was

  CONFIG_FILES    = 
  CONFIG_HEADERS  = 
  CONFIG_LINKS    = 
  CONFIG_COMMANDS = 
  $ ./config.status 

on Elfworks

config.status:794: creating Makefile
config.status:966: executing depfiles commands
configure:5424: === configuring in qucs (/home/bobby/Downloads/qucs-0.0.19/qucs)
configure:5487: running /bin/bash ./configure --disable-option-checking '--prefix=/usr/local'  --cache-file=/dev/null --srcdir=.
configure:5492: error: ./configure failed for qucs

## ---------------- ##
## Cache variables. ##
## ---------------- ##

ac_cv_build=x86_64-unknown-linux-gnu
ac_cv_c_compiler_gnu=yes
ac_cv_cxx_compiler_gnu=yes
ac_cv_env_CCC_set=
ac_cv_env_CCC_value=
ac_cv_env_CC_set=
ac_cv_env_CC_value=
ac_cv_env_CFLAGS_set=
ac_cv_env_CFLAGS_value=
ac_cv_env_CPPFLAGS_set=
ac_cv_env_CPPFLAGS_value=
ac_cv_env_CXXFLAGS_set=
ac_cv_env_CXXFLAGS_value=
ac_cv_env_CXX_set=
ac_cv_env_CXX_value=
ac_cv_env_LDFLAGS_set=
ac_cv_env_LDFLAGS_value=
ac_cv_env_LIBS_set=
ac_cv_env_LIBS_value=
ac_cv_env_build_alias_set=
ac_cv_env_build_alias_value=
ac_cv_env_host_alias_set=
ac_cv_env_host_alias_value=
ac_cv_env_target_alias_set=
ac_cv_env_target_alias_value=
ac_cv_host=x86_64-unknown-linux-gnu
ac_cv_objext=o
ac_cv_path_install='/usr/bin/install -c'
ac_cv_path_mkdir=/bin/mkdir
ac_cv_prog_AWK=gawk
ac_cv_prog_ac_ct_CC=gcc
ac_cv_prog_ac_ct_CXX=g++
ac_cv_prog_cc_c89=
ac_cv_prog_cc_g=yes
ac_cv_prog_cxx_g=yes
ac_cv_prog_make_make_set=yes
am_cv_CC_dependencies_compiler_type=none
am_cv_CXX_dependencies_compiler_type=none
am_cv_make_support_nested_variables=yes
am_cv_prog_cc_c_o=yes

## ----------------- ##
## Output variables. ##
## ----------------- ##

ACLOCAL='${SHELL} /home/bobby/Downloads/qucs-0.0.19/missing aclocal-1.15'
AMDEPBACKSLASH='\'
AMDEP_FALSE='#'
AMDEP_TRUE=''
AMTAR='$${TAR-tar}'
AM_BACKSLASH='\'
AM_DEFAULT_V='$(AM_DEFAULT_VERBOSITY)'
AM_DEFAULT_VERBOSITY='1'
AM_V='$(V)'
AUTOCONF='${SHELL} /home/bobby/Downloads/qucs-0.0.19/missing autoconf'
AUTOHEADER='${SHELL} /home/bobby/Downloads/qucs-0.0.19/missing autoheader'
AUTOMAKE='${SHELL} /home/bobby/Downloads/qucs-0.0.19/missing automake-1.15'
AWK='gawk'
CC='gcc'
CCDEPMODE='depmode=none'
CFLAGS='-g -O2'
COND_MACOSX_FALSE=''
COND_MACOSX_TRUE='#'
CPPFLAGS=''
CXX='g++'
CXXDEPMODE='depmode=none'
CXXFLAGS='-g -O2'
CYGPATH_W='echo'
DEFS='-DPACKAGE_NAME=\"qucs\" -DPACKAGE_TARNAME=\"qucs\" -DPACKAGE_VERSION=\"0.0.19\" -DPACKAGE_STRING=\"qucs\ 0.0.19\" -DPACKAGE_BUGREPORT=\"qucs-bugs@lists.sourceforge.net\" -DPACKAGE_URL=\"\" -DPACKAGE=\"qucs\" -DVERSION=\"0.0.19\"'
DEPDIR='.deps'
ECHO_C=''
ECHO_N='-n'
ECHO_T=''
ENABLE_DOC_FALSE='#'
ENABLE_DOC_TRUE=''
EXEEXT=''
INSTALL_DATA='${INSTALL} -m 644'
INSTALL_PROGRAM='${INSTALL}'
INSTALL_SCRIPT='${INSTALL}'
INSTALL_STRIP_PROGRAM='$(install_sh) -c -s'
LDFLAGS=''
LIBOBJS=''
LIBS=''
LTLIBOBJS=''
MAKEINFO='${SHELL} /home/bobby/Downloads/qucs-0.0.19/missing makeinfo'
MKDIR_P='/bin/mkdir -p'
OBJEXT='o'
PACKAGE='qucs'
PACKAGE_BUGREPORT='qucs-bugs@lists.sourceforge.net'
PACKAGE_NAME='qucs'
PACKAGE_STRING='qucs 0.0.19'
PACKAGE_TARNAME='qucs'
PACKAGE_URL=''
PACKAGE_VERSION='0.0.19'
PATH_SEPARATOR=':'
QUCS_TEST_FALSE='#'
QUCS_TEST_TRUE=''
SET_MAKE=''
SHELL='/bin/bash'
STRIP=''
VERSION='0.0.19'
ac_ct_CC='gcc'
ac_ct_CXX='g++'
am__EXEEXT_FALSE=''
am__EXEEXT_TRUE='#'
am__fastdepCC_FALSE=''
am__fastdepCC_TRUE='#'
am__fastdepCXX_FALSE=''
am__fastdepCXX_TRUE='#'
am__include='include'
am__isrc=''
am__leading_dot='.'
am__nodep='_no'
am__quote=''
am__tar='$${TAR-tar} chof - "$$tardir"'
am__untar='$${TAR-tar} xf -'
bindir='${exec_prefix}/bin'
build='x86_64-unknown-linux-gnu'
build_alias=''
build_cpu='x86_64'
build_os='linux-gnu'
build_vendor='unknown'
datadir='${datarootdir}'
datarootdir='${prefix}/share'
docdir='${datarootdir}/doc/${PACKAGE_TARNAME}'
dvidir='${docdir}'
exec_prefix='${prefix}'
host='x86_64-unknown-linux-gnu'
host_alias=''
host_cpu='x86_64'
host_os='linux-gnu'
host_vendor='unknown'
htmldir='${docdir}'
includedir='${prefix}/include'
infodir='${datarootdir}/info'
install_sh='${SHELL} /home/bobby/Downloads/qucs-0.0.19/install-sh'
libdir='${exec_prefix}/lib'
libexecdir='${exec_prefix}/libexec'
localedir='${datarootdir}/locale'
localstatedir='${prefix}/var'
mandir='${datarootdir}/man'
mkdir_p='$(MKDIR_P)'
oldincludedir='/usr/include'
pdfdir='${docdir}'
prefix='/usr/local'
program_transform_name='s,x,x,'
psdir='${docdir}'
runstatedir='${localstatedir}/run'
sbindir='${exec_prefix}/sbin'
sharedstatedir='${prefix}/com'
subdirs=' qucs qucs-core qucs-doc'
sysconfdir='${prefix}/etc'
target_alias=''

configure: exit 1

**Comment by felix-salfelder** [comment]
> subdirs=' qucs qucs-core qucs-doc'

actually, (for some reason) there are two nested `qucs` packages. one consists of 3 packages related to qucs, the other is the qucs gui (the one that failed to configure). you find the logfile for the latter in `$builddir/qucs/config.log`. i guess your builddir is `/home/bobby/Downloads/qucs-0.0.19/`

(sorry for the confusion)

**Comment by plomlompom** [comment]
I've had a similar issue (same "checking for Qt library... configure: error: not found") on the current Debian stable. In my case, the solution was to also install the libqt4-opengl-dev package, despite it not being listed in the README's list of dependencies.

**Comment by felix-salfelder** [comment]
@plomlompom thanks.

did libqt4-opengl-dev pull in libqt4-opengl? maybe that one is somehow checked for (or required, but why?).

**Comment by 1greyghost** [comment]
plomlompom (Christian), YOU ARE THE MAN!

Installing 'libqt4-opengl-dev', allowed me to configure, with an exit value of 0.  Now I am in the process of making and installing.
--

Whoops, I noticed a lot of warnings about deprecated lines of code during the 'make and install', and I ended up getting an error.

The last several lines of the 'make and install' are, as follows:

    GEAR1 error constants: 2-step, order 1, error constant 1
            0   0   1
    GEAR2 error constants: 3-step, order 2, error constant 1
            0   0   0   1
    GEAR3 error constants: 4-step, order 3, error constant 1
            0.00000   0.00000   0.00000  -0.00000   1.00000
    GEAR4 error constants: 5-step, order 4, error constant 1
            0.00000   0.00000   0.00000  -0.00000   0.00000   1.00000
    GEAR5 error constants: 6-step, order 5, error constant 1
            0.00000   0.00000   0.00000   0.00000   0.00000  -0.00000   1.00000
    GEAR6 error constants: 7-step, order 6, error constant 1
            0.00000   0.00000   0.00000   0.00000   0.00000  -0.00000   0.00000   1.00000
    /usr/bin/octave --path . coplanarzl.m
    Graphic reduced !
    export TEXINPUTS=.:./..:./..:; : -interaction=nonstopmode technical.tex
    export BIBINPUTS=.:; /usr/bin/bibtex technical
    I couldn't open file name `technical.aux'
    Makefile:585: recipe for target 'technical.dvi' failed
    make[2]: *** [technical.dvi] Error 1
    make[2]: Leaving directory '/home/bobby/Downloads/qucs-0.0.19/qucs-doc/technical'
    Makefile:383: recipe for target 'install-recursive' failed
    make[1]: *** [install-recursive] Error 1
    make[1]: Leaving directory '/home/bobby/Downloads/qucs-0.0.19/qucs-doc'
    Makefile:381: recipe for target 'install-recursive' failed
    make: *** [install-recursive] Error 1

**Comment by plomlompom** [comment]
@felix-salfelder: I just tried with mere libqt4-opengl, but that only failed with `checking for Qt library... configure: error: not found` again.

@1greyghost: Glad it helped a bit at least. The error you encounter also looks familiar. I think I overcame it by running `./configure` with the `--disable-doc` flag.

**Comment by 1greyghost** [comment]
@plomlompom: running './configure --disable-doc' did the trick.  I had no trouble with the 'make' and everything installed correctly.  Thanks!
