### ISSUE TITLE
Support of Android OS

### ISSUE THREAD

**Issue by eldarkg** [Qucs/qucs#726]
It'll be good if Qucs can run on Android devices.

**Comment by guitorri** [comment]
It would be good. 
Qt5 is needed to be able to support Android.
Work is in progress to get rid of Qt3Support. So first we have to get to Qt4 and then Qt5.
It might take a while. 
Closing for now.

**Comment by felix-salfelder** [comment]
On Thu, Dec 13, 2018 at 12:27:05AM -0800, Samuel Emmett Bray wrote:
> why migrate to qt4 at all? 

qt5.

qt4 is dead. see
https://alioth-lists.debian.net/pipermail/pkg-electronics-devel/2018-June/005055.html
(same applies to other os'es and distros)

cheers
