### ISSUE TITLE
N mutual inductors AC model is broken

### ISSUE THREAD

**Issue by in3otd** [Qucs/qucs#738]
The N mutual inductors AC model seems broken, see the post on the `qucs-help` mailing list.
Schematics showing the issue enclosed.
[mutx.zip](https://github.com/Qucs/qucs/files/1383339/mutx.zip)

**Comment by guitorri** [comment]
Context:
https://sourceforge.net/p/qucs/mailman/message/36074669/

**Comment by ra3xdh** [comment]
See #741 fox fix
