### ISSUE TITLE
Stylesheet pushbutton break layout

### ISSUE THREAD

**Issue by yodalee** [Qucs/qucs#74]
Related to #69.
To make pushbutton with background color work on Mac OS and Windows (even some Linux), I use stylesheet to fill the color in pushbutton. However, this destroy the size of pushbutton and layout, as shown in the photo below.
https://cloud.githubusercontent.com/assets/1388949/4800913/371ce0b6-5e2b-11e4-9086-0532201287d8.png

---

The code in #135 could be applied to:
- Paintings
  - [x] line
  - [x] arrow #135
  - [x] Text
  - [x] filled / Ellipse
  - [x] filled / Rectangle
  - [x] Arc
- Diagrams Properties
  - [x] Data color
  - [x] Properties, Grid color
- File > Application Settings
  - [x] Document Background Color

**Comment by guitorri** [comment]
This kind of fixed the issue on the diagram properties: https://github.com/Qucs/qucs/issues/30
