### ISSUE TITLE
Snap support

### ISSUE THREAD

**Issue by BearzRobotics** [Qucs/qucs#765]
On your website I see that the team officially supports Ubuntu with a ppa, I was wondering if you guys were planning on also making it snap. The snap has the advantage of not having to add a pp, plus its install able on other distros like Solus, Debian, arch, etc (Any that support snapd). Plus Launchpad has support for creating snaps on multiple architectures from ppas.

**Comment by eldarkg** [comment]
@BearzRobotics You can see src of snap package here https://github.com/eldarkg/qucs-spice-snap.
This package contains qucs-spice branch.

**Comment by guitorri** [comment]
I guess someone (developer or not) has to step up and maintain this packaging system. 
If there is something that needs to be added to our repository, by no means, let us know and we will put in under contrib. Closing for now.
