### ISSUE TITLE
qucsconv is not working under Linux

### ISSUE THREAD

**Issue by Kathy626** [Qucs/qucs#790]
Hey, all
I have met a problem relates to qucsconv in Linux.
I've tried to use qucscpnv to convert a touchstone file (s38p) into qucsdata file (dat), this command works totally fine in my Windows machine, but it errored out in Linux, and I have attached error message in here:
![image](https://user-images.githubusercontent.com/37670623/37803379-a678c086-2deb-11e8-9c06-060780bd6e67.png)
Does anybody has met this problem before?

**Comment by Kathy626** [comment]
I've found out that since the touchstone file I am using is s38p file, which for each frequency point is 38 x 38 matrix. Not sure whether Linux qucs has the ability to handle this big file

**Comment by in3otd** [comment]
these errors come from the routine that parses the S-parameters file; it may be somehow related to #789.
I'm currently doing some simulations with a 36-port S-parameters file and it works fine in Linux - could be faster probably but the results are ok.
The problem *might* be related to the line terminations, you could try to change that using `dos2unix` or similar and see if it makes a difference. 
It will of course be useful if you could share a stripped-down/reduced version of the problematic file.

**Comment by Kathy626** [comment]
thanks a lot, very very helpful

2018-03-27 12:11 GMT-07:00 in3otd <notifications@github.com>:

**Comment by Kathy626** [comment]
Which file you'd like me to share? the reduced touchstone file or compiled code?

**Comment by in3otd** [comment]
I'd like to have a Touchstone file which you are not able to convert on Linux so I can try to use that to debug this issue locally.

**Comment by Kathy626** [comment]
The file is too big to upload, even after I zip the file still too big.
The touchstone file I have is 38 ports (s38p), with 1315 frequency sweep points.

**Comment by Kathy626** [comment]
​
 Test_sparams_38ports.zip
<https://drive.google.com/file/d/1Z09_rcd2lg_VXzbbrOINgkgxuYM_5v9g/view?usp=drive_web>
​does this work?

2018-03-27 13:30 GMT-07:00 in3otd <notifications@github.com>:

**Comment by in3otd** [comment]
thanks for the file; here I'm able to convert it without errors both in Linux and Windows. I've run a quick simulation, the results seem a bit strange (magnitude often >> 1 and not smooth) but I guess this may be ok. Not sure where the problem could be there; you may try to reduce your file to just 1 or 2 frequency points and see if it works fine.

**Comment by Kathy626** [comment]
Ok, maybe the version is the reason causing this strange thing. Because,
from my downloaded QUCS Linux package, Bison is 2.7, flex is 2.5.37

But I am so confused of how you could observe the similar error when you
compiling QUCS with Bison Grammar, this should not affect

2018-03-29 12:15 GMT-07:00 in3otd <notifications@github.com>:

**Comment by Kathy626** [comment]
Thanks. By the way, do you know how to change Bison version for qucs?

**Comment by in3otd** [comment]
`bison` is using only when compiling Qucs to build the parser source code; if you update your Bison version you need to recompile Qucs to see if the new version works differently. How to update Bison depends on the Linux distribution.
