### ISSUE TITLE
Distribution through flathub?

### ISSUE THREAD

**Issue by dineshdb** [Qucs/qucs#797]
Flathub provides easy installation procedure for almost all Linux platforms. Currently, qucs version available through fedora repos is 0.0.18 whereas it was not even available in Ubuntu some times ago. It would be better if an alternative like flathub is considered.

**Comment by guitorri** [comment]
I guess one has to step up and maintain this packaging system. If there is something that needs to be added to our repository, by no means, let us know and we will put in under contrib.
