### ISSUE TITLE
Change Qucs Home lead to empty schematic tab, unusable

### ISSUE THREAD

**Issue by guitorri** [Qucs/qucs#834]
Steps to reproduce:

- Build `release-0.0.20` branch and run Qucs
- Open one project/schematic from current Qucs Home location
- Change Qucs Home
  - File > App Settings > Locations (tab) > [Browse to another Qucs Home] > OK
- Problems 
  - schematic tab becomes empty, no Tab widget on view. It is not possible to open projects from the new Qucs Home.
  - app cannot be closed (File > Quit)

Tested on macOS 10.12.6

**Comment by in3otd** [comment]
yep, it seems to work fine if you create a new empty schematic manually...
