### ISSUE TITLE
Unable to run ngspice, xyce, opusspice simulators.

### ISSUE THREAD

**Issue by aishaque** [Qucs/qucs#867]
![screenshot from 2018-09-16 20-48-58](https://user-images.githubusercontent.com/37832828/45598391-bf73db80-b9f4-11e8-9806-b312ecbe15c1.png)
Hi,

I am running Ubuntu 18.04. I have installed qucs -spice on my system through the software store. When I try to use ngspice ,  xyce or opusspice as a default simulator and run simulation I get the error "Failed to start the simulator" (screenshot attached). I have all three of these installed on my system and working. In fact, I am able to use these simulators in qucs_s0.0.20, which is a fork of a qucs project. Can you help me in sorting this?

Regards, Amir

**Comment by ra3xdh** [comment]
I am not maintaining the Snap package for Qucs-S and Qucs. I remember that @eldarkg created the Snap for Qucs-S. Probably he can help you. Please use the Qucs-S bugtracker https://github.com/ra3xdh/qucs_s/issues to report Qucs-S related issues.
