### ISSUE TITLE
build is broken

### ISSUE THREAD

**Issue by andres-erbsen** [Qucs/qucs#875]
~~~~~
/home/travis/build/Qucs/qucs/qucs/qucs/qucs.cpp:1229:24: error: ‘slotUpdateTreeview’ was not declared in this scope
     slotUpdateTreeview();
~~~~~

https://travis-ci.org/Qucs/qucs/jobs/432061091#L2219

**Comment by in3otd** [comment]
yep, due to interactions between two PRs merged recently the `develop` branch does not build.
Fix is in #871 - for the moment you can also simply delete the line referenced above containing the call to `slotUpdateTreeview()` as that function was removed since no longer needed.
