### ISSUE TITLE
PDF bounding box wrong

### ISSUE THREAD

**Issue by Rmano** [Qucs/qucs#882]
Hi, 
I have (I do not know how) managed to create a `.sch` file which has the bounding box of the exported PDF wrong. Exporting in `png` and `eps` works ok, but the PDF is quite strange: 

![image](https://user-images.githubusercontent.com/6414907/49223324-c2208300-f3de-11e8-8a57-95059d64c955.png)

I am using: `Qucs 0.0.20 (a7597048f)` (compiled here, Ubuntu 18.04). 

Files: /home/romano/lib/qucs/sallenkey_prj/BW3k-ok.sch
[test.zip](https://github.com/Qucs/qucs/files/2629198/test.zip)

**Comment by in3otd** [comment]
yes, can be reproduced also here: with *File->Export as image...* you get a `pdf` with the wrong bounding box. It works fine when using *File->Print...*. Seems to have something to do with using `inkscape` for the conversion, I'm taking a look.

**Comment by Rmano** [comment]
Sorry for the delay; checked, works ok. Thanks.!
