### ISSUE TITLE
Parameter Sweep is not working

### ISSUE THREAD

**Issue by deiltonrm** [Qucs/qucs#919]
I setup just a very simple circuit in order to check the parameter sweep is working or not.
I got this error message regarding to 'SweepModel' property.
Please, let know what is wrong ?

Starting new simulation on sex 03. mai 2019 at 12:07:26:933

creating netlist... done.
Starting /snap/qucs-spice/4/usr/bin/qucsator

project location: 
modules to load: 0
factorycreate.size() is 0
factorycreate has registered:
parsing netlist...
checking netlist...

Errors occurred during simulation on sex 03. mai 2019 at 12:07:26:971
Aborted.

line 6: checker error, extraneous property `SweepModel' is invalid in `SW:SW1'
line 6: checker error, no such variable `false' used in a `SW:SW1' property

![Captura de tela de 2019-05-03 12-08-12](https://user-images.githubusercontent.com/49407053/57147214-7151f380-6d9d-11e9-8763-f19b2008ae27.png)

Deilton Martins

**Comment by ra3xdh** [comment]
This can happen if you are trying to open the schematic saved by Qucs-S using Qucs. Currently there is no way to fix it automatically. The *.sch files are XML. Open the *.sch file with the text editor and remove the "SweepModel" property.

Also the SNAP package for Ubuntu probably was not updated. Use the classic repositories or DEB packages. You can find the full list here https://ra3xdh.github.io/

Use the Qucs-S bugtracker  https://github.com/ra3xdh/qucs_s/issues to report issues for Qucs-S.
