### ISSUE TITLE
CMake or not?

### ISSUE THREAD

**Issue by Kezii** [Qucs/qucs#922]
I see that there are two ways for building qucs, why is this? The latest discussion I was able to find on this matter took place more than a year ago, and today I managed to build qucs without issues with cmake, so what is missing? When the autotools thing will be ditched?

**Comment by in3otd** [comment]
> why is this?

Historical reasons. Qucs initially used the autotools and cmake support was added later.

> I managed to build qucs without issues with cmake

yes, we try to keep both the cmake and autotools build systems working

> When the autotools thing will be ditched?

not sure, likely when there will be a significant immediate advantage in doing so. For the moment we rely on the autotools for building and testing.
