### ISSUE TITLE
Format Error: Unknown component Pac

### ISSUE THREAD

**Issue by Zedonboy** [Qucs/qucs#940]
I changed the default simulator to ngspice, am getting this error in qucs. and i tried opening a schematic file that contains filter generated by filter synthesis tool

**Comment by ra3xdh** [comment]
Pac component belongs to S-parameter simulation. The S-parameter simulation is not supported in Qucs-S using the Ngspice backend. Use the usual AC-analysis instead. You will need to edit the auto-synthesized circuit manually.

**Comment by ra3xdh** [comment]
Use the Qucs-S bugtracker to report issues related Qucs-S: http://github.com/ra3xdh/qucs_s/issues
