### ISSUE TITLE
migrating python2 to python3 in test modules

### ISSUE THREAD

**Issue by oxmon-2500** [Qucs/qucs#950]
qucs-test contains some python modules in python2 syntax. 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
./qucs-test/qucstest/__init__.py
./qucs-test/qucstest/colors.py
./qucs-test/qucstest/misc.py
./qucs-test/qucstest/qucsator.py
./qucs-test/qucstest/figures.py
./qucs-test/qucstest/netlist.py
./qucs-test/qucstest/qucsdata.py
./qucs-test/qucstest/qucsgui.py
./qucs-test/qucstest/report.py
./qucs-test/qucstest/schematic.py
./qucs-test/test/test.py
./qucs-test/parse_equations.py
./qucs-test/parse_models.py
./qucs-test/qmat.py
./qucs-test/run_equations.py
./qucs-test/run.py
Migration already done in local environment

**Comment by guitorri** [comment]
Duplicate https://github.com/Qucs/qucs-test/issues/33
Can you make a PR with the changes?

**Comment by oxmon-2500** [comment]
OK, after I'm ready with all tests, I will make a PR

**Comment by oxmon-2500** [comment]
The changes and tests are done.

**Comment by guitorri** [comment]
Fixed on #968
