### ISSUE TITLE
TRAVIS CI build could not complete (ccache not found on osx)

### ISSUE THREAD

**Issue by oxmon-2500** [Qucs/qucs#959]
TRAVIS osx continuous-integration/travis-ci/pr — The Travis CI build could not complete

$ **ccache --version**

 **ccache: command not found**

pull/953#partial-pull-merging

I suppose it must be done by a maintainer. I made some research and there is probably a solution:
https://www.redhat.com/archives/libvir-list/2018-May/msg02216.html
File: .travis.yml
PATH="/usr/local/opt/ccache/libexec:$PATH"
brew install ccache

**Comment by in3otd** [comment]
yes, that's likely needed. I think there may be something else needing a fix, see [here].(https://github.com/Qucs/qucs/pull/946#issuecomment-573878052)

If you wish, you can do another PR with that fix; Travis will run on that and we will see if the macOS build completes successfully.

**Comment by guitorri** [comment]
Fixed on #968
