### ISSUE TITLE
Copyright date in help is still on 2016

### ISSUE THREAD

**Issue by Rmano** [Qucs/qucs#978]
This is a very minor thing, but... I just compiled the release-0.0.20 branch on Ubuntu 18.04 (without problems --- great! Thanks everybody!) and on "About..." I have:

![image](https://user-images.githubusercontent.com/6414907/75631344-508f4000-5bf2-11ea-8b43-e2dd6b307a08.png)

...I think it's worth correcting, but I don't think it's worth a PR... ;-)

**Comment by in3otd** [comment]
oops :grin:
I think there might be other places with the wrong year (I think I saw something in the CMakefiles @guitorri recently modified).

And by the way, I'd maybe put Stefan Jahn name too in the second (C) line, as he wrote the simulator (`qucsator`), which is still the only simulator Qucs supports...

**Comment by felix-salfelder** [comment]
>  ...I think it's worth correcting, but I don't think it's worth a PR... ;-)

done.

yes, there might be other places, and yes Stefan Jahn wrote qucsator. open new tickets please.
