### ISSUE TITLE
"linblocks" tutorial is not in the menu...

### ISSUE THREAD

**Issue by Rmano** [Qucs/qucs#980]
Hi, this is probably my fault, but I do not know how to correct it. I have seen that my contributed tutorial about linear blocks and frequency responses has been added (thanks!), but it still doesn't appear in the menu: 

![image](https://user-images.githubusercontent.com/6414907/75633676-4e83ac00-5c07-11ea-8100-5969583de26c.png)

Probably I was supposed to add it somewhere in the sources, but I do not know where... 

Thanks!

**Comment by guitorri** [comment]
Is the file being installed? The menu is filled with whatever files are on the DocDir.

**Comment by Rmano** [comment]
Hmmm... I don't know. I will try to check - should I had put something special in the Makefile or anywhere?

Thanks for helping - - it's not really critical so don't waste time on it, I'll try to look at it when I get some time (probably on Tuesday)

**Comment by guitorri** [comment]
I checked the Makefile.am, it seems fine...

**Comment by felix-salfelder** [comment]
> it's not really critical so don't waste time on it

defer to 0.0.21?

**Comment by Rmano** [comment]
It's ok for me. 
Even better if you change the release to, say, 0.9.0 (`/me ducks`, ;-) --- I know I have already said that, but it's my pet peeve...)

**Comment by felix-salfelder** [comment]
Let's discuss version numbers once 0.0.20 is out. Fingers crossed it will be relevant.
